{
 "title": "reservatório",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "sensores", "label": "sensor", "query": "select id from sensor" }
  ]
 },
 "panels": [
  {
   "title": "Reservatórios",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select r.descricao as Reservatório\n     , s.id as Sensor\n  from sensor s inner join reservatorio r on s.reservatorio_id = r.id\n  where s.id in  ($sensores);"
    }
   ]
  },
  {
   "title": "Nível sensores",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  data_medicao AS \"time\",\n  avg(dado) as ccnt,\n  concat('Sensor ', sensor_id) metric\nFROM medicao\nwhere $__timeFilter(data_medicao)\n  and sensor_id in ($sensores)\ngroup by sensor_id, data_medicao"
    }
   ]
  },
  {
   "title": "Média",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select avg(m.dado)\n  from medicao m\nwhere $__timeFilter(data_medicao)\n  and sensor_id in ($sensores)"
    }
   ]
  },
  {
   "title": "Nível Mínimo Atingido",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select min(m.dado)\n  from medicao m\nwhere $__timeFilter(data_medicao)\n  and sensor_id in ($sensores)"
    }
   ]
  },
  {
   "title": "Nível Máximo Atingido",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select max(m.dado)\n  from medicao m\nwhere $__timeFilter(data_medicao)\n  and sensor_id in ($sensores)"
    }
   ]
  },
  {
   "title": "Nível sensores",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\n  data_medicao AS \"time\",\n  avg(dado) as ccnt,\n  concat('Sensor ', sensor_id) metric\nFROM medicao\nwhere $__timeFilter(data_medicao)\n  and sensor_id in ($sensores)\ngroup by sensor_id, data_medicao"
    }
   ]
  },
  {
   "title": "Nível sensores",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  data_medicao AS \"time\",\n  avg(dado) as ccnt,\n  concat('Sensor ', sensor_id) metric\nFROM medicao\nwhere $__timeFilter(data_medicao)\n  and sensor_id in ($sensores)\ngroup by sensor_id, data_medicao"
    }
   ]
  },
  {
   "title": "Preciptação",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  data_medicao AS \"time\",\n  avg(dado) as ccnt,\n  concat('Sensor ', sensor_id) metric\nFROM medicao\nwhere $__timeFilter(data_medicao)\n  and sensor_id in ($sensores)\n  and tipo = 'P'\ngroup by sensor_id, data_medicao"
    }
   ]
  },
  {
   "title": "Vazão",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  data_medicao AS \"time\",\n  avg(dado) as ccnt,\n  concat('Sensor ', sensor_id) metric\nFROM medicao\nwhere $__timeFilter(data_medicao)\n  and sensor_id in ($sensores)\n  and tipo = 'V'\ngroup by sensor_id, data_medicao"
    }
   ]
  }
 ]
}